import { splitAnswerAndCitations } from "@/lib/citations";
import { scoreAnswerGroundedness } from "@/lib/groundedness";
import { downloadText } from "@/lib/export";

function safeName(title: string) {
  return title.replace(/[^\w\-]+/g, "-").replace(/-+/g, "-").slice(0, 40) || "trust-receipt";
}

/** One-page “trust receipt” — unique PaperPilot artifact for sharing/printing. */
export function buildTrustReceipt(opts: {
  title: string;
  question: string;
  answer: string;
  documentNames: string;
  documentText: string;
}) {
  const { body, citations, doNext, confidence } = splitAnswerAndCitations(opts.answer);
  const g = scoreAnswerGroundedness(opts.answer, opts.documentText);
  const lines = [
    `# PaperPilot Trust Receipt`,
    "",
    `Chat: ${opts.title}`,
    `Generated: ${new Date().toLocaleString()}`,
    `Sources: ${opts.documentNames}`,
    "",
    `## Question`,
    "",
    opts.question || "_n/a_",
    "",
    `## Answer`,
    "",
    body || opts.answer,
    "",
    `## Truth meter`,
    "",
    `- Groundedness: ${g.label} (${g.score}%) — ${g.detail}`,
    `- Model confidence: ${confidence || "not reported"}`,
    "",
  ];
  if (doNext?.keyPoints.length) {
    lines.push("## Key points", "");
    for (const p of doNext.keyPoints) lines.push(`- ${p}`);
    lines.push("");
  }
  if (citations.length) {
    lines.push("## Verified source quotes", "");
    for (const c of citations) {
      lines.push(`- **${c.document}:** “${c.quote}”`);
    }
    lines.push("");
  }
  lines.push(
    "---",
    "",
    "_This receipt was generated by PaperPilot. Quotes are matched against extracted text on your device; always open the original document for legal or high-stakes use._",
    "",
  );
  return lines.join("\n");
}

export function exportTrustReceipt(opts: {
  title: string;
  question: string;
  answer: string;
  documentNames: string;
  documentText: string;
}) {
  downloadText(
    `${safeName(opts.title)}-receipt.md`,
    buildTrustReceipt(opts),
    "text/markdown;charset=utf-8",
  );
}
